from enum import IntFlag

class CyclingPowerFlags(IntFlag):
    PEDAL_POWER_BALANCE_PRESENT = 1<<0
    PEDAL_POWER_BALANCE_REFERENCE = 1<<1
    ACCUMULATED_TORQUE_PRESENT = 1<<2
    ACCUMULATED_TORQUE_SOURCE = 1<<3
    WHEEL_REVOLUTION_DATA_PRESENT = 1<<4
    CRANK_REVOLUTION_DATA_PRESENT =1<<5
    EXTREME_FORCE_MAGNITUDES_PRESENT = 1<<6
    EXTREME_TORQUE_MAGNITUDES_PRESENT = 1<<7
    EXTREME_ANGLES_PRESENT = 1<<8
    TOP_DEAD_SPOT_ANGLE_PRESENT = 1<<9
    BOTTOM_DEAD_SPOT_ANGLE_PRESENT = 1<<10
    ACCUMULATED_ENERGY_PRESENT = 1<<11
    OFFSET_COMPENSATION_INDICATOR = 1<<12
