# Generated by Django 5.2.1 on 2025-05-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='tasks.task')),
            ],
        ),
    ]
